version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  api:
    build:
      context: ./Anomologita.Api
    container_name: anomologita-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=Anomologita;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=Anomologita
      - Jwt__Audience=AnomologitaAudience
    ports:
      - "5015:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  sql_data: